apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-crb
roleRef:
  kind: ClusterRole
  name: fluentd-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd-sa
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    instrumentation: fluentd
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      instrumentation: fluentd
  template:
    metadata:
      labels:
        instrumentation: fluentd
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluentd-sa
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "es-cluster-es-default"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENT_ELASTICSEARCH_USER
              value: "admin"
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              value: "changeme"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
            - name: config
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: fluentd-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-pvc
  labels:
    instrumentation: fluentd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
