apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.2/components.yaml
  - kubernetes-dashboard.yaml
  - fluentd.yaml
  - kibana.yaml
  - elasticsearch.yaml
  - jaeger.yaml
  - otel-collector.yaml
  - grafana.yaml
  - prometheus.yaml

configMapGenerator:
  - name: fluentd-config
    files:
      - config/fluent.conf
  - name: grafana-datasource-config
    files:
      - config/datasource.yaml
  - name: jaeger-config
    files:
      - config/jaeger-ui.json
  - name: otel-collector-config
    files:
      - config/otel-collector-config.yaml
  - name: prometheus-config
    files:
      - config/prometheus.yaml
