apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    instrumentation: otel-collector
  name: otel-collector-d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      instrumentation: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        instrumentation: otel-collector
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yaml
          image: otel/opentelemetry-collector:0.67.0
          name: otel-collector
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 8889
          resources:
            limits:
              cpu: 750m
              memory: 50Mi
            requests:
              cpu: 250m
              memory: 10Mi
          volumeMounts:
            - name: config
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    instrumentation: otel-collector
  name: otel-collector-service
spec:
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: exporter
      port: 8889
      targetPort: 8889
  selector:
    instrumentation: otel-collector
