apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      logging:

      prometheus:
        endpoint: "0.0.0.0:8889"

      otlp:
        endpoint: "jaeger-collector:4317"
        tls:
          insecure: true

    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
