apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    instrumentation: prometheus
  name: prometheus-d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      instrumentation: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        instrumentation: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.41.0
          name: prometheus
          ports:
            - containerPort: 9090
            - containerPort: 31923
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 20Mi
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yaml
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    instrumentation: prometheus
  name: prometheus-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    instrumentation: prometheus
