apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: dev
  name: local-storage
  labels:
    app: auth
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: dev
spec:
  selfSigned: {}