apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: dev
  name: local-storage
  labels:
    app: article
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
