apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-cert
spec:
  isCA: true
  commonName: root-cert
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: root-issuer
spec:
  ca:
    secretName: root-secret
