resources:
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
  - service_account_database.yaml
  - role_binding_database.yaml
  - role_database.yaml
  - namespace.yaml

helmCharts:
  - name: community-operator
    namespace: mongodb
    repo: https://mongodb.github.io/helm-charts
    version: 0.12.0
    includeCRDs: true
    valuesInline:
      operator:
        watchNamespace: "*"
