apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  labels:
    instrumentation: grafana
  name: grafana-d
spec:
  replicas: 1
  selector:
    matchLabels:
      instrumentation: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: dev
      labels:
        instrumentation: grafana
    spec:
      containers:
        - env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
          image: grafana/grafana:9.3.2
          name: grafana
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 250m
              memory: 75Mi
            requests:
              cpu: 50m
              memory: 20Mi
          volumeMounts:
            - name: grafana-dashboards
              mountPath: /var/lib/grafana
            - name: grafana-datasource-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
      restartPolicy: Always
      volumes:
        - name: grafana-dashboards
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasource-config
          configMap:
            name: grafana-datasource-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  labels:
    instrumentation: grafana
  name: grafana-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    instrumentation: grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  labels:
    instrumentation: grafana
  namespace: dev
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service:9090
      isDefault: true
      access: proxy
      editable: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    instrumentation: grafana
spec: 
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
      - ReadWriteOnce
