resources:
  - ../../base
  - namespace.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: customTransformer
      namespace: stage
    unsetOnly: true
