resources:
  - ../../base
  - namespace.yaml

components:
  - ../../components/tls
  - ../../components/telemetry

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: customTransformer
      namespace: stage
    unsetOnly: true
