resources:
  - self-signed-issuer.yaml
  - fluentd.yaml
  - kibana.yaml
  - elasticsearch.yaml
  - jaeger.yaml
  - rabbitmq.yaml
  - local-storage.yaml
  - otel-collector.yaml
  - grafana.yaml
  - prometheus.yaml
  - ca.yaml
