apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  image: rabbitmq:3.11.3-alpine
  secretBackend:
    externalSecret:
      name: "rabbitmq-credentials-secret"
  service:
    type: LoadBalancer
  replicas: 1
  resources:
    limits:
      cpu: 750m
      memory: 200Mi
    requests:
      cpu: 250m
      memory: 50Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials-secret
type: Opaque
stringData:
  default_user.conf: |
    default_user = guest
    default_pass = guest
