resources:
  - ../../base
  - namespace.yaml
  - local-storage.yaml

components:
  - ../../components/tls

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: customTransformer
      namespace: dev
    unsetOnly: true
