resources:
  - dev-namespace.yaml
  - ../../vendor
  - ../../base

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: customNamespaceTransformer
      namespace: dev
    unsetOnly: true
